version: '3'
services:
  node:
    build:
      context: ./docker-build
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd my-app && yarn dev"
    ports:
      - "1234:1234"
    stdin_open: true
